void start()
{
  memory.u1 = 0xBBAALL;
  memory.u2 = 0xDDCCLL;
  memory.u3 = 0xFFEELL;
  memory.u4 = 0xADDELL;
  memory.u5 = 0xEFBELL;
  memory.u6 = 0xFECALL;
  memory.u7 = 0xBEBALL;
  memory.u8 = 0xCDABLL;

  memory.b1 = 'rB';
  memory.b2 = 'ia';
  memory.b3 = 'Nn';
  memory.b4 = 'mu';
  memory.b5 = 'Fb';
  memory.b6 = 'or';
  memory.b7 = 'Vm';
  memory.b8 = '!m';

  memory.lu1 = memory.u1 | (memory.u2 << 16) | (memory.u3 << 32) | (memory.u4 << 48);
  memory.lu2 = memory.u5 | (memory.u6 << 16) | (memory.u7 << 32) | (memory.u8 << 48);

  memory.lb1 = memory.b1 | (memory.b2 << 16) | (memory.b3 << 32) | (memory.b4 << 48);
  memory.lb2 = memory.b5 | (memory.b6 << 16) | (memory.b7 << 32) | (memory.b8 << 48);

  memory.i = 0LL;
  memory.repeat = 1LL;
  memory.nmatch = 0LL;
  memory.ok_ = 0LL;

  // strcmp(user, internal_buffer)
  while ( memory.repeat == 1 )
  {
    if ( memory.i < 8 )
    {
      memory.uw = (unsigned __int64)memory.lu1 >> (8 * (unsigned __int8)memory.i);
      memory.bw = (unsigned __int64)memory.lb1 >> (8 * (unsigned __int8)memory.i);
    }

    if ( memory.i > 7 )
    {
      memory.uw = (unsigned __int64)memory.lu2 >> (8 * (unsigned __int8)memory.i);
      memory.bw = (unsigned __int64)memory.lb2 >> (8 * (unsigned __int8)memory.i);
    }
    memory.uw = (unsigned __int8)memory.uw;
    memory.bw = (unsigned __int8)memory.bw;

    if ( memory.uw != memory.bw )
      memory.repeat = 0LL;

    if ( memory.uw == memory.bw )
      ++memory.nmatch;

    if ( ++memory.i > 15 )
      memory.repeat = 0LL;
  }

  if ( memory.nmatch == 16 )
  {
    memory.ok_ = 1LL;

    memory.msg[0] = ' ';
    print_rax();
    memory.msg[1] = ' ';
    print_rax();
    memory.msg[2] = '_';
    print_rax();
    memory.msg[3] = ' ';
    print_rax();
    memory.msg[4] = ' ';
    print_rax();
    memory.msg[5] = ' ';
    print_rax();
    memory.msg[6] = ' ';
    print_rax();
    memory.msg[7] = '_';
    print_rax();
    memory.msg[8] = ' ';
    print_rax();
    memory.msg[9] = ' ';
    print_rax();
    memory.msg[10] = ' ';
    print_rax();
    memory.msg[11] = ' ';
    print_rax();
    memory.msg[12] = '_';
    print_rax();
    memory.msg[13] = ' ';
    print_rax();
    memory.msg[14] = ' ';
    print_rax();
    memory.msg[15] = ' ';
    print_rax();
    memory.msg[16] = ' ';
    print_rax();
    memory.msg[17] = '_';
    print_rax();
    memory.msg[18] = 32LL;
    print_rax();
    memory.msg[19] = 32LL;
    print_rax();
    memory.msg[20] = 32LL;
    print_rax();
    memory.msg[21] = 32LL;
    print_rax();
    memory.msg[22] = 95LL;
    print_rax();
    memory.msg[23] = 32LL;
    print_rax();
    memory.msg[24] = 32LL;
    print_rax();
    memory.msg[25] = 32LL;
    print_rax();
    memory.msg[26] = 32LL;
    print_rax();
    memory.msg[27] = 95LL;
    print_rax();
    memory.msg[28] = 13LL;
    print_rax();
    memory.msg[29] = 10LL;
    print_rax();
    memory.msg[30] = 32LL;
    print_rax();
    memory.msg[31] = 47LL;
    print_rax();
    memory.msg[32] = 32LL;
    print_rax();
    memory.msg[33] = 92LL;
    print_rax();
    memory.msg[34] = 32LL;
    print_rax();
    memory.msg[35] = 32LL;
    print_rax();
    memory.msg[36] = 47LL;
    print_rax();
    memory.msg[37] = 32LL;
    print_rax();
    memory.msg[38] = 92LL;
    print_rax();
    memory.msg[39] = 32LL;
    print_rax();
    memory.msg[40] = 32LL;
    print_rax();
    memory.msg[41] = 47LL;
    print_rax();
    memory.msg[42] = 32LL;
    print_rax();
    memory.msg[43] = 92LL;
    print_rax();
    memory.msg[44] = 32LL;
    print_rax();
    memory.msg[45] = 32LL;
    print_rax();
    memory.msg[46] = 47LL;
    print_rax();
    memory.msg[47] = 32LL;
    print_rax();
    memory.msg[48] = 92LL;
    print_rax();
    memory.msg[49] = 32LL;
    print_rax();
    memory.msg[50] = 32LL;
    print_rax();
    memory.msg[51] = 47LL;
    print_rax();
    memory.msg[52] = 32LL;
    print_rax();
    memory.msg[53] = 92LL;
    print_rax();
    memory.msg[54] = 32LL;
    print_rax();
    memory.msg[55] = 32LL;
    print_rax();
    memory.msg[56] = 47LL;
    print_rax();
    memory.msg[57] = 32LL;
    print_rax();
    memory.msg[58] = 92LL;
    print_rax();
    memory.msg[59] = 13LL;
    print_rax();
    memory.msg[60] = 10LL;
    print_rax();
    memory.msg[61] = 40LL;
    print_rax();
    memory.msg[62] = 32LL;
    print_rax();
    memory.msg[63] = 117LL;
    print_rax();
    memory.msg[64] = 32LL;
    print_rax();
    memory.msg[65] = ')';
    print_rax();
    memory.msg[66] = '(';
    print_rax();
    memory.msg[67] = ' ';
    print_rax();
    memory.msg[68] = 'n';
    print_rax();
    memory.msg[69] = ' ';
    print_rax();
    memory.msg[70] = ')';
    print_rax();
    memory.msg[71] = '(';
    print_rax();
    memory.msg[72] = ' ';
    print_rax();
    memory.msg[73] = 'd';
    print_rax();
    memory.msg[74] = ' ';
    print_rax();
    memory.msg[75] = ')';
    print_rax();
    memory.msg[76] = '(';
    print_rax();
    memory.msg[77] = ' ';
    print_rax();
    memory.msg[78] = '3';
    print_rax();
    memory.msg[79] = ' ';
    print_rax();
    memory.msg[80] = ')';
    print_rax();
    memory.msg[81] = '(';
    print_rax();
    memory.msg[82] = ' ';
    print_rax();
    memory.msg[83] = 'r';
    print_rax();
    memory.msg[84] = ' ';
    print_rax();
    memory.msg[85] = ')';
    print_rax();
    memory.msg[86] = '(';
    print_rax();
    memory.msg[87] = ' ';
    print_rax();
    memory.msg[88] = '_';
    print_rax();
    memory.msg[89] = ' ';
    print_rax();
    memory.msg[90] = ')';
    print_rax();
    memory.msg[91] = '\r';
    print_rax();
    memory.msg[92] = '\n';
    print_rax();
    memory.msg[93] = ' ';
    print_rax();
    memory.msg[94] = '\\';
    print_rax();
    memory.msg[95] = '_';
    print_rax();
    memory.msg[96] = '/';
    print_rax();
    memory.msg[97] = ' ';
    print_rax();
    memory.msg[98] = ' ';
    print_rax();
    memory.msg[99] = '\\';
    print_rax();
    memory.msg[100] = '_';
    print_rax();
    memory.msg[101] = '/';
    print_rax();
    memory.msg[102] = ' ';
    print_rax();
    memory.msg[103] = ' ';
    print_rax();
    memory.msg[104] = '\\';
    print_rax();
    memory.msg[105] = '_';
    print_rax();
    memory.msg[106] = '/';
    print_rax();
    memory.msg[107] = ' ';
    print_rax();
    memory.msg[108] = ' ';
    print_rax();
    memory.msg[109] = '\\';
    print_rax();
    memory.msg[110] = '_';
    print_rax();
    memory.msg[111] = 47LL;
    print_rax();
    memory.msg[112] = 32LL;
    print_rax();
    memory.msg[113] = 32LL;
    print_rax();
    memory.msg[114] = 92LL;
    print_rax();
    memory.msg[115] = 95LL;
    print_rax();
    memory.msg[116] = 47LL;
    print_rax();
    memory.msg[117] = 32LL;
    print_rax();
    memory.msg[118] = 32LL;
    print_rax();
    memory.msg[119] = 92LL;
    print_rax();
    memory.msg[120] = 95LL;
    print_rax();
    memory.msg[121] = 47LL;
    print_rax();
    memory.msg[122] = 13LL;
    print_rax();
    memory.msg[123] = 10LL;
    print_rax();
    memory.msg[124] = 32LL;
    print_rax();
    memory.msg[125] = 32LL;
    print_rax();
    memory.msg[126] = 95LL;
    print_rax();
    memory.msg[127] = 32LL;
    print_rax();
    memory.msg[128] = 32LL;
    print_rax();
    memory.msg[129] = 32LL;
    print_rax();
    memory.msg[130] = ' ';
    print_rax();
    memory.msg[131] = 95LL;
    print_rax();
    memory.msg[132] = 32LL;
    print_rax();
    memory.msg[133] = 32LL;
    print_rax();
    memory.msg[134] = 32LL;
    print_rax();
    memory.msg[135] = 32LL;
    print_rax();
    memory.msg[136] = 95LL;
    print_rax();
    memory.msg[137] = 32LL;
    print_rax();
    memory.msg[138] = 32LL;
    print_rax();
    memory.msg[139] = 32LL;
    print_rax();
    memory.msg[140] = 32LL;
    print_rax();
    memory.msg[141] = 95LL;
    print_rax();
    memory.msg[142] = 32LL;
    print_rax();
    memory.msg[143] = 32LL;
    print_rax();
    memory.msg[144] = 32LL;
    print_rax();
    memory.msg[145] = 32LL;
    print_rax();
    memory.msg[146] = 95LL;
    print_rax();
    memory.msg[147] = 32LL;
    print_rax();
    memory.msg[148] = 32LL;
    print_rax();
    memory.msg[149] = 32LL;
    print_rax();
    memory.msg[150] = 32LL;
    print_rax();
    memory.msg[151] = 95LL;
    print_rax();
    memory.msg[152] = 32LL;
    print_rax();
    memory.msg[153] = 32LL;
    print_rax();
    memory.msg[154] = 32LL;
    print_rax();
    memory.msg[155] = 32LL;
    print_rax();
    memory.msg[156] = 95LL;
    print_rax();
    memory.msg[157] = 32LL;
    print_rax();
    memory.msg[158] = 32LL;
    print_rax();
    memory.msg[159] = 32LL;
    print_rax();
    memory.msg[160] = 32LL;
    print_rax();
    memory.msg[161] = 95LL;
    print_rax();
    memory.msg[162] = 32LL;
    print_rax();
    memory.msg[163] = 32LL;
    print_rax();
    memory.msg[164] = 32LL;
    print_rax();
    memory.msg[165] = 32LL;
    print_rax();
    memory.msg[166] = 95LL;
    print_rax();
    memory.msg[167] = 32LL;
    print_rax();
    memory.msg[168] = 32LL;
    print_rax();
    memory.msg[169] = 32LL;
    print_rax();
    memory.msg[170] = 32LL;
    print_rax();
    memory.msg[171] = 95LL;
    print_rax();
    memory.msg[172] = 32LL;
    print_rax();
    memory.msg[173] = 32LL;
    print_rax();
    memory.msg[174] = 32LL;
    print_rax();
    memory.msg[175] = 32LL;
    print_rax();
    memory.msg[176] = 95LL;
    print_rax();
    memory.msg[177] = 32LL;
    print_rax();
    memory.msg[178] = 32LL;
    print_rax();
    memory.msg[179] = 32LL;
    print_rax();
    memory.msg[180] = 32LL;
    print_rax();
    memory.msg[181] = 95LL;
    print_rax();
    memory.msg[182] = '\r';
    print_rax();
    memory.msg[183] = '\n';
    print_rax();
    memory.msg[184] = ' ';
    print_rax();
    memory.msg[185] = '/';
    print_rax();
    memory.msg[186] = ' ';
    print_rax();
    memory.msg[187] = '\\';
    print_rax();
    memory.msg[188] = ' ';
    print_rax();
    memory.msg[189] = ' ';
    print_rax();
    memory.msg[190] = '/';
    print_rax();
    memory.msg[191] = ' ';
    print_rax();
    memory.msg[192] = '\\';
    print_rax();
    memory.msg[193] = ' ';
    print_rax();
    memory.msg[194] = ' ';
    print_rax();
    memory.msg[195] = '/';
    print_rax();
    memory.msg[196] = ' ';
    print_rax();
    memory.msg[197] = 92LL;
    print_rax();
    memory.msg[198] = 32LL;
    print_rax();
    memory.msg[199] = 32LL;
    print_rax();
    memory.msg[200] = 47LL;
    print_rax();
    memory.msg[201] = 32LL;
    print_rax();
    memory.msg[202] = 92LL;
    print_rax();
    memory.msg[203] = 32LL;
    print_rax();
    memory.msg[204] = 32LL;
    print_rax();
    memory.msg[205] = 47LL;
    print_rax();
    memory.msg[206] = 32LL;
    print_rax();
    memory.msg[207] = 92LL;
    print_rax();
    memory.msg[208] = 32LL;
    print_rax();
    memory.msg[209] = 32LL;
    print_rax();
    memory.msg[210] = 47LL;
    print_rax();
    memory.msg[211] = 32LL;
    print_rax();
    memory.msg[212] = 92LL;
    print_rax();
    memory.msg[213] = 32LL;
    print_rax();
    memory.msg[214] = 32LL;
    print_rax();
    memory.msg[215] = 47LL;
    print_rax();
    memory.msg[216] = 32LL;
    print_rax();
    memory.msg[217] = 92LL;
    print_rax();
    memory.msg[218] = 32LL;
    print_rax();
    memory.msg[219] = 32LL;
    print_rax();
    memory.msg[220] = 47LL;
    print_rax();
    memory.msg[221] = 32LL;
    print_rax();
    memory.msg[222] = 92LL;
    print_rax();
    memory.msg[223] = 32LL;
    print_rax();
    memory.msg[224] = 32LL;
    print_rax();
    memory.msg[225] = 47LL;
    print_rax();
    memory.msg[226] = 32LL;
    print_rax();
    memory.msg[227] = 92LL;
    print_rax();
    memory.msg[228] = 32LL;
    print_rax();
    memory.msg[229] = 32LL;
    print_rax();
    memory.msg[230] = 47LL;
    print_rax();
    memory.msg[231] = 32LL;
    print_rax();
    memory.msg[232] = 92LL;
    print_rax();
    memory.msg[233] = 32LL;
    print_rax();
    memory.msg[234] = 32LL;
    print_rax();
    memory.msg[235] = 47LL;
    print_rax();
    memory.msg[236] = 32LL;
    print_rax();
    memory.msg[237] = 92LL;
    print_rax();
    memory.msg[238] = 32LL;
    print_rax();
    memory.msg[239] = 32LL;
    print_rax();
    memory.msg[240] = 47LL;
    print_rax();
    memory.msg[241] = 32LL;
    print_rax();
    memory.msg[242] = 92LL;
    print_rax();
    memory.msg[243] = 13LL;
    print_rax();
    memory.msg[244] = 10LL;
    print_rax();
    memory.msg[245] = 40LL;
    print_rax();
    memory.msg[246] = 32LL;
    print_rax();
    memory.msg[247] = 99LL;
    print_rax();
    memory.msg[248] = 32LL;
    print_rax();
    memory.msg[249] = 41LL;
    print_rax();
    memory.msg[250] = 40LL;
    print_rax();
    memory.msg[251] = 32LL;
    print_rax();
    memory.msg[252] = 48LL;
    print_rax();
    memory.msg[253] = 32LL;
    print_rax();
    memory.msg[254] = 41LL;
    print_rax();
    memory.msg[255] = 40LL;
    print_rax();
    memory.msg[256] = 32LL;
    print_rax();
    memory.msg[257] = 110LL;
    print_rax();
    memory.msg[258] = 32LL;
    print_rax();
    memory.msg[259] = 41LL;
    print_rax();
    memory.msg[260] = 40LL;
    print_rax();
    memory.msg[261] = 32LL;
    print_rax();
    memory.msg[262] = 115LL;
    print_rax();
    memory.msg[263] = 32LL;
    print_rax();
    memory.msg[264] = 41LL;
    print_rax();
    memory.msg[265] = 40LL;
    print_rax();
    memory.msg[266] = 32LL;
    print_rax();
    memory.msg[267] = 116LL;
    print_rax();
    memory.msg[268] = 32LL;
    print_rax();
    memory.msg[269] = 41LL;
    print_rax();
    memory.msg[270] = 40LL;
    print_rax();
    memory.msg[271] = 32LL;
    print_rax();
    memory.msg[272] = 114LL;
    print_rax();
    memory.msg[273] = 32LL;
    print_rax();
    memory.msg[274] = 41LL;
    print_rax();
    memory.msg[275] = 40LL;
    print_rax();
    memory.msg[276] = 32LL;
    print_rax();
    memory.msg[277] = 117LL;
    print_rax();
    memory.msg[278] = 32LL;
    print_rax();
    memory.msg[279] = 41LL;
    print_rax();
    memory.msg[280] = 40LL;
    print_rax();
    memory.msg[281] = 32LL;
    print_rax();
    memory.msg[282] = 99LL;
    print_rax();
    memory.msg[283] = 32LL;
    print_rax();
    memory.msg[284] = 41LL;
    print_rax();
    memory.msg[285] = 40LL;
    print_rax();
    memory.msg[286] = 32LL;
    print_rax();
    memory.msg[287] = 116LL;
    print_rax();
    memory.msg[288] = 32LL;
    print_rax();
    memory.msg[289] = 41LL;
    print_rax();
    memory.msg[290] = 40LL;
    print_rax();
    memory.msg[291] = 32LL;
    print_rax();
    memory.msg[292] = 105LL;
    print_rax();
    memory.msg[293] = 32LL;
    print_rax();
    memory.msg[294] = 41LL;
    print_rax();
    memory.msg[295] = 40LL;
    print_rax();
    memory.msg[296] = 32LL;
    print_rax();
    memory.msg[297] = 48LL;
    print_rax();
    memory.msg[298] = 32LL;
    print_rax();
    memory.msg[299] = 41LL;
    print_rax();
    memory.msg[300] = 40LL;
    print_rax();
    memory.msg[301] = 32LL;
    print_rax();
    memory.msg[302] = 110LL;
    print_rax();
    memory.msg[303] = 32LL;
    print_rax();
    memory.msg[304] = 41LL;
    print_rax();
    memory.msg[305] = 13LL;
    print_rax();
    memory.msg[306] = 10LL;
    print_rax();
    memory.msg[307] = 32LL;
    print_rax();
    memory.msg[308] = 92LL;
    print_rax();
    memory.msg[309] = 95LL;
    print_rax();
    memory.msg[310] = 47LL;
    print_rax();
    memory.msg[311] = 32LL;
    print_rax();
    memory.msg[312] = 32LL;
    print_rax();
    memory.msg[313] = 92LL;
    print_rax();
    memory.msg[314] = 95LL;
    print_rax();
    memory.msg[315] = 47LL;
    print_rax();
    memory.msg[316] = 32LL;
    print_rax();
    memory.msg[317] = 32LL;
    print_rax();
    memory.msg[318] = 92LL;
    print_rax();
    memory.msg[319] = 95LL;
    print_rax();
    memory.msg[320] = 47LL;
    print_rax();
    memory.msg[321] = 32LL;
    print_rax();
    memory.msg[322] = 32LL;
    print_rax();
    memory.msg[323] = 92LL;
    print_rax();
    memory.msg[324] = 95LL;
    print_rax();
    memory.msg[325] = 47LL;
    print_rax();
    memory.msg[326] = 32LL;
    print_rax();
    memory.msg[327] = 32LL;
    print_rax();
    memory.msg[328] = 92LL;
    print_rax();
    memory.msg[329] = 95LL;
    print_rax();
    memory.msg[330] = 47LL;
    print_rax();
    memory.msg[331] = 32LL;
    print_rax();
    memory.msg[332] = 32LL;
    print_rax();
    memory.msg[333] = 92LL;
    print_rax();
    memory.msg[334] = 95LL;
    print_rax();
    memory.msg[335] = 47LL;
    print_rax();
    memory.msg[336] = 32LL;
    print_rax();
    memory.msg[337] = 32LL;
    print_rax();
    memory.msg[338] = 92LL;
    print_rax();
    memory.msg[339] = 95LL;
    print_rax();
    memory.msg[340] = 47LL;
    print_rax();
    memory.msg[341] = 32LL;
    print_rax();
    memory.msg[342] = 32LL;
    print_rax();
    memory.msg[343] = 92LL;
    print_rax();
    memory.msg[344] = 95LL;
    print_rax();
    memory.msg[345] = 47LL;
    print_rax();
    memory.msg[346] = 32LL;
    print_rax();
    memory.msg[347] = 32LL;
    print_rax();
    memory.msg[348] = 92LL;
    print_rax();
    memory.msg[349] = 95LL;
    print_rax();
    memory.msg[350] = 47LL;
    print_rax();
    memory.msg[351] = 32LL;
    print_rax();
    memory.msg[352] = 32LL;
    print_rax();
    memory.msg[353] = 92LL;
    print_rax();
    memory.msg[354] = 95LL;
    print_rax();
    memory.msg[355] = 47LL;
    print_rax();
    memory.msg[356] = 32LL;
    print_rax();
    memory.msg[357] = 32LL;
    print_rax();
    memory.msg[358] = 92LL;
    print_rax();
    memory.msg[359] = '_';
    print_rax();
    memory.msg[360] = '/';
    print_rax();
    memory.msg[361] = ' ';
    print_rax();
    memory.msg[362] = ' ';
    print_rax();
    memory.msg[363] = '\\';
    print_rax();
    memory.msg[364] = '_';
    print_rax();
    memory.msg[365] = '/';
    print_rax();
    memory.msg[365] = '\r';
    print_rax();
    memory.msg[365] = '\n';
    print_rax();
  }
  check = memory.ok_;
}